plugins:
  - jekyll-remote-theme
remote_theme: daviddarnes/alembic

exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - vendor
  - .jekyll-cache
  - .bundle

paginate: 2
paginate_path: blog/page:num
author: camerondavison
social:
  name: Cameron Davison
  links:
    - https://www.linkedin.com/in/camerondavison
    - https://github.com/daviddarnes

sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: America/Chicago

collections:
  posts:
    title: Cameron Davison
    output: true
    description: "Random Notes and Thoughts"
    feature_image: "/img/unicycle.jpg"

defaults:
  - scope:
      path: ""
    values:
      image: "/assets/default-social-image.png"

encoding: utf-8
lang: en-US
title: "Cameron Davison" # Site name or title, also used in jekyll-seo-tag
description: "Random Notes and Thoughts"
url: "https://camerondavison.com"
baseurl: ""
repo: "https://github.com/camerondavison/camerondavison.com"
email: "cameron.davison@gmail.com"
google_analytics: "UA-176821237-1"
disqus: "camerondavison"
css_inline: true

navigation_header:
  - title: Home
    url: /

navigation_footer:
  - title: Created by Cameron Davison
    url: https://camerondavison.com

social_links:
  LinkedIn: https://www.linkedin.com/in/camerondavison
  GitHub: https://github.com/camerondavison
  RSS: /feed.xml
