theme: jekyll-theme-minimal

title: Cameron Davison
description: Random Notes and Thoughts

permalink: /:year-:month-:day-:title/

# adds /drafts/:title/ pages
collections:
  drafts:
    output: true
